import './header';
import './tabsModels';
import './tabsMalfunction'
import './article';
import './slider';
import './accordion';
import './accordionFaq';
import './accordionPrice';
import './accordionContactsGeneral';
import './map';
import './mobile-menu';
import './modal';